#!/bin/bash -e
#
# Copyright 2008 by Scott S. Goodwin

# We always want to be in top level directory
cd $(dirname $0)

source config.sh

PGSTOP="$PGBIN/pg_ctl -w stop -D $PGDATA"
PGSTART="$PGBIN/pg_ctl -w start -D $PGDATA -l $SITEROOT/logs/postgres.log"

case $1 in
	start)
		if [ ! -f "$PGDATA/PG_VERSION" ] && [ "$1" != "init" ]; then
			echo "Initializing PGDATA area (only performed once)"
			echo ""
			$PGBIN/initdb -D $PGDATA --locale=C --encoding=UTF-8 -L $PGSHARE -A trust
		fi
		$PGSTART
		;;
	stop)
		$PGSTOP
		;;
	create)
		$PGBIN/createdb $PGDATABASE
		$PGBIN/createlang pltcl $PGDATABASE
		$PGBIN/createlang plpgsql $PGDATABASE
		;;
	drop)
		$PGBIN/dropdb $PGDATABASE
		;;
	destroy)
		$PGSTOP
		/bin/rm -r $PGDATA
		;;
	#dump)
	#	/bin/mkdir -p $ONEMIS/tmp/dbdump
	#	$PGBIN/pg_dump --format=p --disable-triggers --schema-only $PGDATABASE > $ONEMIS/tmp/dbdump/${PGDATABASE}.schema.sql
	#	$PGBIN/pg_dump --format=p --disable-triggers --data-only   $PGDATABASE > $ONEMIS/tmp/dbdump/${PGDATABASE}.data.sql
	#	$PGBIN/pg_dump --format=p --disable-triggers               $PGDATABASE > $ONEMIS/tmp/dbdump/${PGDATABASE}.complete.sql
	#	;;
	#load)
	#	$PGBIN/psql -f $ONEMIS/tmp/dbdump/${PGDATABASE}.complete.sql
	#	;;
	status)
		$PGBIN/pg_ctl status -D $PGDATA
		;;
	hup)
		$PGBIN/pg_ctl reload -D $PGDATA
		;;
	#get)
	#	# XXX FIX AFTER WE'VE MOVED TO OPERATIONS - paths are wrong for new way, but work with old
	#	###rsync -atv --rsh="ssh -p 8443 -l onemis" --delete onemis.nasa.gov:/home/onemis/sql/DB/dump /home/onemis/sql/DB
	#	;;
	*)
		echo "$0: unknown subcommand: $@"
		;;
esac

