#!/bin/bash -e
#
# Copyright 2008 by Scott S. Goodwin

# We always want to be in top level directory
cd $(dirname $0)

source config.sh

if [ ! -z "$2" ]; then
	source $2/config.sh
fi

if [ -z "$SITENAME" ]; then
	source default/config.sh
fi

case $1 in
	start)
		if [ ! -L "$NSROOT/servers/$SITENAME" ]; then
			/bin/rm -rf $NSROOT/servers/$SITENAME
			/bin/ln -s $SITEROOT/$SITENAME $NSROOT/servers
		fi
		$NSROOT/bin/nsd \
			$NS_DEBUG \
			-t $SITEROOT/$SITENAME/nsd.tcl \
			-u $SITEOWNER \
			-g $SITEGROUP \
			-s $SITENAME \
			-b $NS_ADDRESS:$NS_HTTPPORT,$NS_ADDRESS:$NS_HTTPSPORT,$NS_ADDRESS:$NS_HTTPSPORT_PKI
		;;

	gdb)
		 gdb -x gdbinit $NSROOT/bin/nsd
		;;

	stop)
		if [ -f $NSD_LOG ]; then
			kill -TERM $(cat $NSD_LOG)
		else
			echo "Could not find $NSD_LOG"
		fi
		;;

	*)
		echo "$0: unknown subcommand: $@"
		;;
esac

