#!/bin/bash -e
#
# Copyright 2008 by Scott S. Goodwin

# We always want to be in top level directory
cd $(dirname $0)

source config.sh
source $SITEPATH/config.sh

case $1 in
	start)
		/bin/rm -f $NSROOT/servers/$SITENAME
		echo "Linking $SITEPATH -> $NSROOT/server/$SITENAME"
		/bin/ln -s $SITEPATH $NSROOT/servers
		$NSROOT/bin/nsd \
			$NS_DEBUG \
			-t $SITEROOT/config/nsd.tcl \
			-u $SITEOWNER \
			-g $SITEGROUP \
			-s $SITENAME \
			-b $NS_ADDRESS:$NS_HTTPPORT,$NS_ADDRESS:$NS_HTTPSPORT,$NS_ADDRESS:$NS_HTTPSPORT_PKI
		;;

	stop)
		if [ -f $NSD_LOG ]; then
			kill -TERM $(cat $NSD_LOG)
		else
			echo "Could not find $NSD_LOG"
		fi
		;;

	*)
		echo "$0: unknown subcommand: $@"
		;;
esac

