#!/bin/bash

export TCLSH_CMD="$SITEROOT/exe/tcl/bin/tclsh8.4"
export TCLLIBPATH="$SITEROOT/exe/tcl/lib/tcl8.4"

if [ -f nsconfig.tcl ]; then
    $TCLSH_CMD nsconfig.tcl -install $SITEROOT/exe/$NAME -debug
else
    ./configure \
        --prefix=$SITEROOT/exe/aolserver \
        --with-tcl=$SITEROOT/exe/tcl/lib
fi

make
make install

